{% set name = "mup" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mup-{{ version }}.tar.gz
  sha256: 9639e3d19f90e754f985ed444542ed2f8a049f3c0488fcb6efe150f30922cf74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pytorch
    - torchvision
    - seaborn
    - tqdm
    - pyyaml

test:
  imports:
    - mup
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/mup
  summary: Maximal Update Parametrization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
